namespace:
  name: staging
replicaCount: 3

service:
  type: ClusterIP
  port: 5111
  targetPort: 3111
  protocol: TCP

resources:
  requests:
    memory: "90Mi"
    cpu: "300m"
  limits:
    memory: "128Mi"
    cpu: "500m"
