namespace: sandbox
replicaCount: 1

image:
  repository: techtrends
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4111
  targetPort: 3111
  protocol: TCP

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe: 
  path: /healthz
